version: '3'
services:
  apigateway:
    image: "idawud/turntablapigateway:latest"
    env_file:
    - .envs/.apigateway
    ports:
      - "80:8081"
      - "443:8081"
  permission:
    image: "idawud/accperm:v3"
    env_file:
      - .envs/.permission
    ports:
      - "5000:5000"
  gis:
    image: "isammyk/gis-docker:latest"
    env_file:
      - .envs/.gis
    ports:
      - "5004:5004"
  chess:
    image: "francisbilla/chess:latest"
    env_file:
      - .envs/.chess
    ports: 
      - "8080:8080" 
  holiday:
    image: "billalidocker/holiday:latest"
    env_file:
      - .envs/.holiday
    ports:  
      - "7070:7070" 
  empire:
    image: "0275309199/empire:latest" 
    env_file:
      - .envs/.empire
    ports:
      - "8050:8050" 
