version: '3'
services:
  apigateway:
    image: "idawud/turntablapigateway:latest"
    env_file:
    - .envs/.apigateway
    ports:
      - "80:8081"
  permission:
    image: "idawud/accperm:v3"
    env_file:
      - .envs/.permission
    ports:
      - "5000:5000"
  gis:
    image: "isammyk/gis-docker:latest"
    env_file:
      - .envs/.gis
    ports:
      - "5004:5004"
  chess:
    image: "926377470665.dkr.ecr.us-east-2.amazonaws.com/chess:latest"
    env_file:
      - .envs/.chess
    ports: 
      -"8080:8080"    
